add stringify plain object
bramstein/url-template pull request #26
Opened 2020-07-18 10:09 UTC by belyy2910

2020-07-24 09:48 UTC, belyy2910 commented
At present "expand" method can't handle custom objects with string representation like MongoDB ObjectId. Just correcting condition and adding missed stringify in "getValues" method fixed the issue

2022-01-28 17:19 UTC, jonkoops requested changes
I'd also like to see some test cases added for the specific types of object that would require this kind of behavior.

2022-01-28 17:19 UTC, jonkoops commented on package.json
> +    "is-plain-object": "=3.0.1"
Not a fan of introducing external dependencies for such a small change, can we do this internally instead?

2022-02-23 14:21 UTC, jonkoops commented
Closing this PR due to lack of response from the author. If there is still interest in working on this feel free to open up a new PR, or ping me and I can re-open this one.

2022-02-23 14:21 UTC, closed without merging